name: .NET Core CI

on:
  push:
    branches: [ "main", "develop" ]

  pull_request:
    branches: [ "master" ]
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          POSTGRES_DB: recipecatalog
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restaurar dependencias NuGet
      run: dotnet restore

    - name: Compilar solución
      run: dotnet build --no-restore --configuration Release

    - name: Ejecutar Pruebas
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: dotnet test --no-build --configuration Release --verbosity normal
